import type { CatalogItem } from "@layra/types";

// Dimensions in metres. gltfUrl records the intended asset path; until those
// exist, the renderer draws a box from footprint and height.
export const CATALOG: CatalogItem[] = [
  {
    id: "sofa-3",
    name: "Sofa (3 seat)",
    gltfUrl: "/models/sofa-3.glb",
    footprint: { w: 2.1, d: 0.9 },
    height: 0.8,
    wallMounted: false,
    clearance: { front: 0.7, sides: 0.1, back: 0 },
  },
  {
    id: "armchair",
    name: "Armchair",
    gltfUrl: "/models/armchair.glb",
    footprint: { w: 0.85, d: 0.85 },
    height: 0.8,
    wallMounted: false,
    clearance: { front: 0.6, sides: 0.15, back: 0 },
  },
  {
    id: "bed-double",
    name: "Bed (double)",
    gltfUrl: "/models/bed-double.glb",
    footprint: { w: 1.6, d: 2.05 },
    height: 0.55,
    wallMounted: false,
    clearance: { front: 0.7, sides: 0.6, back: 0 },
  },
  {
    id: "dining-table",
    name: "Dining table",
    gltfUrl: "/models/dining-table.glb",
    footprint: { w: 1.6, d: 0.9 },
    height: 0.75,
    wallMounted: false,
    clearance: { front: 0.75, sides: 0.75, back: 0.75 },
  },
  {
    id: "dining-chair",
    name: "Dining chair",
    gltfUrl: "/models/dining-chair.glb",
    footprint: { w: 0.45, d: 0.5 },
    height: 0.9,
    wallMounted: false,
    clearance: { front: 0.4, sides: 0.05, back: 0.3 },
  },
  {
    id: "desk",
    name: "Desk",
    gltfUrl: "/models/desk.glb",
    footprint: { w: 1.4, d: 0.7 },
    height: 0.75,
    wallMounted: false,
    clearance: { front: 0.8, sides: 0.1, back: 0 },
  },
  {
    id: "wardrobe",
    name: "Wardrobe",
    gltfUrl: "/models/wardrobe.glb",
    footprint: { w: 1.2, d: 0.6 },
    height: 2.0,
    wallMounted: false,
    clearance: { front: 0.9, sides: 0, back: 0 },
  },
  {
    id: "bookshelf",
    name: "Bookshelf",
    gltfUrl: "/models/bookshelf.glb",
    footprint: { w: 0.8, d: 0.32 },
    height: 1.8,
    wallMounted: false,
    clearance: { front: 0.6, sides: 0, back: 0 },
  },
  {
    id: "wall-shelf",
    name: "Wall shelf",
    gltfUrl: "/models/wall-shelf.glb",
    footprint: { w: 0.9, d: 0.25 },
    height: 0.3,
    wallMounted: true,
    mountHeight: 1.4,
    clearance: { front: 0.3, sides: 0, back: 0 },
  },
  {
    id: "coffee-table",
    name: "Coffee table",
    gltfUrl: "/models/coffee-table.glb",
    footprint: { w: 1.1, d: 0.6 },
    height: 0.42,
    wallMounted: false,
    clearance: { front: 0.45, sides: 0.1, back: 0.1 },
  },
  {
    id: "tv-stand",
    name: "TV stand",
    gltfUrl: "/models/tv-stand.glb",
    footprint: { w: 1.5, d: 0.42 },
    height: 0.55,
    wallMounted: false,
    clearance: { front: 0.5, sides: 0.1, back: 0 },
  },
  {
    id: "floor-lamp",
    name: "Floor lamp",
    gltfUrl: "/models/floor-lamp.glb",
    footprint: { w: 0.35, d: 0.35 },
    height: 1.7,
    wallMounted: false,
    clearance: { front: 0.1, sides: 0.05, back: 0.1 },
  },
  {
    id: "plant",
    name: "Plant",
    gltfUrl: "/models/plant.glb",
    footprint: { w: 0.45, d: 0.45 },
    height: 1.2,
    wallMounted: false,
    clearance: { front: 0.15, sides: 0.05, back: 0.05 },
  },
  {
    id: "rug",
    name: "Rug",
    gltfUrl: "/models/rug.glb",
    footprint: { w: 1.8, d: 1.2 },
    height: 0.03,
    wallMounted: false,
    clearance: { front: 0, sides: 0, back: 0 },
  },
  {
    id: "kitchen-island",
    name: "Kitchen island",
    gltfUrl: "/models/kitchen-island.glb",
    footprint: { w: 1.6, d: 0.75 },
    height: 0.9,
    wallMounted: false,
    clearance: { front: 0.8, sides: 0.65, back: 0.65 },
  },
  {
    id: "nightstand",
    name: "Nightstand",
    gltfUrl: "/models/nightstand.glb",
    footprint: { w: 0.45, d: 0.4 },
    height: 0.55,
    wallMounted: false,
    clearance: { front: 0.35, sides: 0.05, back: 0 },
  },
  {
    id: "dresser",
    name: "Dresser",
    gltfUrl: "/models/dresser.glb",
    footprint: { w: 1.1, d: 0.5 },
    height: 0.9,
    wallMounted: false,
    clearance: { front: 0.75, sides: 0.05, back: 0 },
  },
  {
    id: "bench",
    name: "Bench",
    gltfUrl: "/models/bench.glb",
    footprint: { w: 1.2, d: 0.45 },
    height: 0.5,
    wallMounted: false,
    clearance: { front: 0.45, sides: 0.08, back: 0.08 },
  },
  {
    id: "ottoman",
    name: "Ottoman",
    gltfUrl: "/models/ottoman.glb",
    footprint: { w: 0.65, d: 0.65 },
    height: 0.45,
    wallMounted: false,
    clearance: { front: 0.35, sides: 0.1, back: 0.1 },
  },
  {
    id: "toilet",
    name: "Toilet",
    gltfUrl: "/models/toilet.glb",
    footprint: { w: 0.4, d: 0.65 },
    height: 0.75,
    wallMounted: false,
    clearance: { front: 0.6, sides: 0.15, back: 0.05 },
  },
  {
    id: "bathtub",
    name: "Bathtub",
    gltfUrl: "/models/bathtub.glb",
    footprint: { w: 1.7, d: 0.75 },
    height: 0.65,
    wallMounted: false,
    clearance: { front: 0.6, sides: 0.35, back: 0.35 },
  },
  {
    id: "wall-mirror",
    name: "Wall mirror",
    gltfUrl: "/models/wall-mirror.glb",
    footprint: { w: 1, d: 0.08 },
    height: 0.9,
    wallMounted: true,
    mountHeight: 1.35,
    clearance: { front: 0.1, sides: 0, back: 0 },
  },
  {
    id: "refrigerator",
    name: "Refrigerator",
    gltfUrl: "/models/refrigerator.glb",
    footprint: { w: 0.9, d: 0.7 },
    height: 2,
    wallMounted: false,
    clearance: { front: 0.9, sides: 0.1, back: 0 },
  },
  {
    id: "stove",
    name: "Stove",
    gltfUrl: "/models/stove.glb",
    footprint: { w: 0.8, d: 0.65 },
    height: 0.9,
    wallMounted: false,
    clearance: { front: 0.8, sides: 0.1, back: 0 },
  },
  {
    id: "kitchen-sink",
    name: "Kitchen sink",
    gltfUrl: "/models/kitchen-sink.glb",
    footprint: { w: 0.8, d: 0.6 },
    height: 0.9,
    wallMounted: false,
    clearance: { front: 0.7, sides: 0.1, back: 0 },
  },
  {
    id: "shower",
    name: "Shower",
    gltfUrl: "/models/shower.glb",
    footprint: { w: 0.9, d: 0.9 },
    height: 2.1,
    wallMounted: false,
    clearance: { front: 0.65, sides: 0.2, back: 0.2 },
  },
  {
    id: "console-table",
    name: "Console table",
    gltfUrl: "/models/console-table.glb",
    footprint: { w: 1.2, d: 0.35 },
    height: 0.8,
    wallMounted: false,
    clearance: { front: 0.45, sides: 0.08, back: 0 },
  },
  {
    id: "beanbag",
    name: "Bean bag",
    gltfUrl: "/models/beanbag.glb",
    footprint: { w: 0.9, d: 0.9 },
    height: 0.6,
    wallMounted: false,
    clearance: { front: 0.45, sides: 0.1, back: 0.1 },
  },
];

export function findCatalogItem(id: string): CatalogItem | undefined {
  return CATALOG.find((item) => item.id === id);
}
